import AxiomChoicePropositionsCanonicalLaneLean.AdmissibleClass
import AxiomChoicePropositionsCanonicalLaneLean.BridgeLemmas
import AxiomChoicePropositionsCanonicalLaneLean.GateLemmas
import AxiomChoicePropositionsCanonicalLaneLean.FinalTheorem
import AxiomChoicePropositionsCanonicalLaneLean.ChoicePrincipleTypes
import AxiomChoicePropositionsCanonicalLaneLean.ChoiceDependentReconstructions
import AxiomChoicePropositionsCanonicalLaneLean.ChoiceContinuityAndConsistency
import AxiomChoicePropositionsCanonicalLaneLean.ChoiceCoherence
import AxiomChoicePropositionsCanonicalLaneLean.ChoiceCanonicalModel
import AxiomChoicePropositionsCanonicalLaneLean.ChoiceRoute
import AxiomChoicePropositionsCanonicalLaneLean.ChoiceFoundationalInhabitants

namespace HautevilleHouse
namespace AxiomChoicePropositionsCanonicalLaneLean

-- This module is the root of the AxiomChoicePropositionsCanonicalLaneLean Lean proof package.

end AxiomChoicePropositionsCanonicalLaneLean
end HautevilleHouse
